language: go

sudo: false

cache:
  directories:
    - $HOME/qemu

env:
  - TRAVIS_GOARCH=arm QEMU_ARCHES=arm
  - TRAVIS_GOARCH=386 QEMU_ARCHES=i386

before_install:
  - export GOARCH=$TRAVIS_GOARCH

before_script:
  - bash -e ci/travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin

script:
  - go build hello.go
  - qemu-$QEMU_ARCHES hello
